### ISSUE TITLE
Help/Suggestion

### ISSUE THREAD

**Issue by lucasoliveira08** [sl34x/ticket-bot#4]
Hello! How are you?

I really like your bot! 

I’m trying to add select menus but I’m not succeeding. It would be nice to be able to add different categories, for example: support, doubts, reports, etc...

I will leave the link of the Discord documentation if you are interested in helping me: [Discord Select menus](https://discordjs.guide/interactions/select-menus.html#building-and-sending-select-menus)

Thank's <3
btw, my discord is Wee#1111

**Comment by sl34x** [comment]
You can accept my request.
